image: php:8.4

stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git libzip-dev zip unzip
  - docker-php-ext-install zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --no-progress

test:
  stage: test
  script:
    - if [ -f composer.lock ]; then vendor/bin/security-checker security:check; fi
    - if [ -f phpunit.xml ] || [ -f phpunit.xml.dist ]; then vendor/bin/phpunit --colors=never; fi
    - if [ -f phpstan.neon ] || [ -f phpstan.dist.neon ]; then vendor/bin/phpstan analyse --memory-limit=2G; fi
    - if [ -f psalm.xml ] || [ -f psalm.xml.dist ]; then vendor/bin/psalm; fi
    - if [ -f .php-cs-fixer.dist.php ]; then vendor/bin/php-cs-fixer fix --dry-run --diff; fi
