services:
    _defaults:
        autowire: true
        autoconfigure: true

    BikeCodersLife\MapBundle\:
        resource: '../../{Command,Service,Controller}'
        tags: ['controller.service_arguments']

    # Register Entities if needed (requires mapping config usually, or auto-mapping)
